# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: "3.8.10"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"
  - script: |
      python -m pip install --upgrade pip
    displayName: "Install dependencies"
  - script: |
      python setup.py sdist
    displayName: "Artifact Creation"
